services:
  database:
    image: postgres
    restart: always
    env_file:
      - ../.env
    volumes:
      - ../database/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - local-network
  app:
    container_name: debug_golang_app
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - database
    env_file:
      - ../.env
    networks:
      - local-network
  file_server:
    container_name: file_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8181:8181
    restart: on-failure
    networks:
      - local-network
    volumes:
    - ../uploads/:/uploads/
networks:
  local-network:
    driver: bridge