services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - /database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
    networks:
      - local-network
  app:
    container_name: golang_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - local-network
networks:
  local-network:
    driver: bridge
